### ISSUE TITLE
usePinch: The first gesture state's 'origin' property on iOS is undefined

### ISSUE THREAD

**Issue by matis-dk** [pmndrs/react-use-gesture#152] opened 2020-04-05 08:50 UTC
When using usePinch, it seems like the `origin` property of the first gesture state on iOS is `undefined`. However, in chrome on desktop it works fine.

Link to code example:
https://codesandbox.io/s/competent-wright-bviyc

**Comment by dbismut** [comment] 2020-04-05 09:09
I’ll have a look. Note that origin is just the center of the gesture, it’s not very useful IMO. What would actually be interesting is getting the origin of the gesture relatively to the element so that you can use it for setting the value of transform-origin but that’s another story.

**Comment by matis-dk** [comment] 2020-04-05 09:24
Agree. Actually, you are describing my use case. 

Currently, I'm calculating the origin relative to the element by adding the scrollTop offset from the scrollview. It seems to work fine. 

Let me know, if I can help you in any way. 

Btw, great piece of work - I enjoy working with this lib so much :clap:

**Comment by dbismut** [comment] 2020-04-05 10:12
Thanks! Well your issue actually drove me to fix a more serious issue (atm the lib was using webkit gesture events for Apple devices even when not using a ref in the `domTarget` option, which resulted in the lib passing incorrect handlers to React).

Anyway, the difficulty here is that I'd still want to use webkit gesture events when possible, which natively handle rotation angle and scaling and support MacBooks trackpads. The problem is that these events don't provide any indication of the touches information separately, so I have to add touch events listeners on top of them.

I'll release `7.0.10` that fixes the collateral issue I've spotted thanks to you, and work on a fix later on for the origin problem.

**Comment by dbismut** [comment] 2020-06-09 22:13
Hey @matis-dk have a look at https://codesandbox.io/s/practical-rosalind-g9hsq which uses `8.0.0-alpha.2`. It should fix the origin issue (finally!).

**Comment by danielkleinert** [comment] 2020-08-11 13:23
The origin is still undefined for Trackpad pinch on macOS Safari. Not only in the first but in all invocations. Is that related?

**Comment by dbismut** [comment] 2020-08-11 13:40
Yes, on a trackpad there's no way to know the position of each finger AFAIK, so you can't calculate the origin. I don't think it would make sense anyway.

**Comment by danielkleinert** [comment] 2020-08-11 15:02
Hmm, I guess what I really wanted is the current mouse location to anchor a zoom. And it looks like the origin is set to the mouse position on Chrome and Firefox, so I expected the same for Safari.

**Comment by dbismut** [comment] 2020-08-11 18:23
I could default to the mouse position I think, that's better than `undefined` you're right.

**Comment by dbismut** [comment] 2020-10-31 22:46
Fixed in v8

**Closed by dbismut** 2020-10-31 22:46 UTC
Labels: bug, minor
