### ISSUE TITLE
useDrag - touches is always 0

### ISSUE THREAD

**Issue by freund17** [pmndrs/react-use-gesture#233] opened 2020-11-24 12:32 UTC
Just wanted to let you know, that since the v8 alpha, `touches` in `useDrag` is always set to `0`.

According to [the documentation](https://use-gesture.netlify.app/docs/state/) it should be set to the "number of fingers touching the screen".

Just wanted to check, whether this new behaviour is intended or not.
Since we have "Multi-target-support" now, I also think it would make more sense to be the "number of fingers touching the target".

**Comment by dbismut** [comment] 2020-11-24 13:39
You're absolutely right, moving to Pointers Events for the drag gesture makes `touches` harder to calculate as Pointer Events don't have that information like Touch Events do, but that's not intended behavior. It is possible that we drop that attribute in the future.

Note that when touches is calculated properly, it's indeed the number of fingers touching the target, not the screen, I had corrected this a while ago but forgot to update the docs 😅

Looking at the code, this makes me realise that this beahvior triggers a bug with this sandbox: https://codesandbox.io/s/multi-gesture-card-rkgzi which becomes dysfunctional when trying to pinch. I need to work on it.

**Comment by jrmi** [comment] 2020-11-28 19:50
> You're absolutely right, moving to Pointers Events for the drag gesture makes `touches` harder to calculate as Pointer Events don't have that information like Touch Events do, but that's not intended behavior. It is possible that we drop that attribute in the future.

I you remove completely this information, how we can be able to differentiate between 1 figer to select things and 2 finger to pan the view ?

**Comment by dbismut** [comment] 2020-11-29 10:02
Indeed you're right. I'll probably have to add state attributes, not sure whether it's going to be a `Set` of `pointerId` or just a counter that I can increment / decrement.

**Comment by dbismut** [comment] 2020-11-29 11:57
Ok I just had a stab at it. Current implementation overwrites touches from `onPinch` so I may have moved the problem elsewhere, but let me know if this fixes it for you at the moment.

Please install version `8.1.0-beta.3`.

**Comment by freund17** [comment] 2020-11-30 11:01
`touches` on `useDrag` seems to work now, however `touches` on `usePinch` is broken now (always `0`).

Sadly, for my usecase I need both to work. (1 and 3 finger drag and pinch to zoom/pan)
Lukily I'm not in a hurry, as the only thing not working right now is the 3 finger drag gesture, which likely noone would have discovered, anyways. ;P

**Comment by dbismut** [comment] 2020-11-30 12:08
@freund17 Can you try beta `8.1.0-beta.6`? The touch logic is not perfect but it should work hopefully.

**Comment by freund17** [comment] 2020-11-30 16:54
Yeah... `touches` seems to be set as expected.

However there seem to be other problems, which prevent me from switching to the beta.
It seems related to `setPointerCapture`...
If that should already be working, I'll create a new issue once I have more information.

**Comment by dbismut** [comment] 2020-11-30 17:35
@freund17 yes setPointerCapture should be working 😅

**Comment by jrmi** [comment] 2020-11-30 21:47
> @freund17 Can you try beta `8.1.0-beta.6`? The touch logic is not perfect but it should work hopefully.

Tested and works for me in my use case, thanks a lot :+1:

**Comment by jrmi** [comment] 2020-12-01 07:35
It may be me, but pinch and pan are not well distinguished if both moves are done with two fingers. Am I missing something ?

**Comment by dbismut** [comment] 2020-12-01 08:18
There's no pan movement par say. Pan is just the drag gesture with two fingers which WILL be triggered whenever you pinch.

I'm a bit overwhelmed atm, I've discovered some bugs with pinch conflicting with drag that I need to solve but it's really not easy (at least to me).

**Comment by jrmi** [comment] 2020-12-01 08:31
Sorry, I would mean drag (not pan) vs pinch, probably the bug you've just mention. I'm not in a hurry, so take your time ;-)

**Comment by freund17** [comment] 2020-12-01 18:38
> @freund17 yes setPointerCapture should be working 😅

I created https://github.com/pmndrs/react-use-gesture/issues/242.

**Comment by dbismut** [comment] 2020-12-02 11:56
@freund17 @jrmi please have a look at beta `8.1.0-beta.8` which should solve most issues related to conflicts between drag and pinch.

**Comment by jrmi** [comment] 2020-12-02 22:00
@dbismut seems much better, touches, drag & pinch at same time. Just a detail, is it normal that distance is always positive even if the finger get closer ?

**Comment by dbismut** [comment] 2020-12-02 22:05
Thanks for testing! Distance is always positive, it's the distance between the two fingers. What you probably want to look at is the distance displacement which is `movement[0]`.

**Comment by Tarpsvo** [comment] 2020-12-03 12:07
Hi! I'm trying out 8.1.0-beta.9 and having an issue where when using `useDrag` the `touches` value is set to 0 even though the touch did not end. I get a few pixels worth of `useDrag` callbacks with the correct value, but then `touches` is reset to 0 again.

**Comment by dbismut** [comment] 2020-12-03 15:11
Hi @Tarpsvo would it be possible to set up a repro sandbox? Thanks!

**Comment by jrmi** [comment] 2020-12-03 19:35
> Thanks for testing! Distance is always positive, it's the distance between the two fingers. What you probably want to look at is the distance displacement which is `movement[0]`.

I'm not sure, but it doesn't seems to be the absolute distance between finger during my tests (I think `da[0]` give that distance) but offset distance since the first touch. If you spread the fingers, the value increase from 0 as expected then if you get your fingers closer, the value decrease to zero then increase again (positively) as you get closer. It can increase until the finger are touching. 

So if this is the absolute distance, why the distance increase when the finger get closer and why it start to 0 value, and if it's the relative distance, it should be negative when finger are closer to initial touch. I'm missing something ?

But indeed movement[0] was the value i was looking for ;-)  thanks a lot !

**Comment by dbismut** [comment] 2020-12-03 20:24
Oh ok, you meant `state.distance`? If so, with the pinch gesture it makes no sense, it's the distance between `da[0]` (which was what I thought you were referring as distance in your earlier message) and `da[1]` the angle. I think I'll remove it from the pinch state to avoid any confusion.

**Comment by jrmi** [comment] 2020-12-03 20:51
Yes that `state.distance`. It was confusing indeed :eyes: Thanks again.

**Comment by Tarpsvo** [comment] 2020-12-08 08:59
Alright, here's a reproducible sandbox @dbismut:

https://codesandbox.io/s/frosty-gareth-fjzlb?file=/src/App.js:322-339

The underlying issue is that on an <img> tag, the gesture ends abruptly. This happens only on version 8 and later. Version 7 works perfectly.

**Comment by dbismut** [comment] 2020-12-08 10:26
@Tarpsvo Have a look: https://codesandbox.io/s/hardcore-wind-f0qrw

I'm not sure about the problem you're facing exactly, but indeed, dragging an image or a link might result in unwanted behavior if you're not styling it appropriately. I would recommend setting the following attributes on your `img` tag to make it work as it should:

```css
-webkit-user-drag: none;
user-select: none;
```

This might not be enough on Firefox (see #188), so you may want to `preventDefault()`. I don't think this is version-specific.

Now a few notes that could be worth mentioning: `down` will be `true` if `touches > 0`. So the check `!down || touches === 0` isn't useful. v9 is also more logical with the `down` attribute, meaning that a gesture can be canceled and still have `down` set to `true`. What you generally want to check is `active` instead (`active === true` if the user is dragging _AND_ the gesture wasn't canceled).

Hope this helps.

**Comment by Tarpsvo** [comment] 2020-12-09 08:10
Thanks for the feedback @dbismut!

How come the exact same Carousel works in version 7 though (without CSS changes)? The older version somehow manages to drag on the images without an issue.

**Comment by dbismut** [comment] 2020-12-09 08:36
@Tarpsvo if I use your sandbox and switch to v7 I get the same unwanted behavior on Safari, Firefox and Chrome on a Mac. The main difference with v8+ is that it starts using Pointer Event vs Mouse and Touch Event.

**Closed** 2021-01-13 16:28 UTC
Labels: bug, fix coming
