### ISSUE TITLE
Swiping does not always work 

### ISSUE THREAD

**Issue by spoldman** [pmndrs/react-use-gesture#249] opened 2020-12-21 22:32 UTC
**Describe the bug**
For some strange reason swiping parameter using drag only works with a mouse and not on an iPhone and sometimes very hard to do using a trackpad on a Mac. Swipe always returns [0,0]. I have tried different options without much success. Works perfectly on Chrome on desktop using a mouse. 

**Sandbox or Video**
https://codesandbox.io/s/rough-bird-33uu4?file=/src/App.js

**Information:**
 - React Use Gesture version: tried v9.0.0-beta.11 and 8.0.1
 - Device: iPhone Xs and Macbook Pro
 - OS: iOS 14.3
 - Browser: Mobile Safari, Chrome  

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment] 2020-12-22 07:44
That's weird your sandbox works perfectly on my iPhone 11 / iOS 14. Do you mind taking a video of your fingers on the actual device if you can?

**Comment by spoldman** [comment] 2020-12-22 10:04
I feel like I'm missing something, but here is a video showing what happens. I know on rare occations it works. But most of the time when I try it if fails on me. I have had some more success with touble finger swiping. But still it does not work very well. 

https://user-images.githubusercontent.com/10643226/102876235-d2c84980-443c-11eb-8742-c477a0c86c28.mov

**Comment by spoldman** [comment] 2020-12-22 10:40
I think the problem is related to velocity. It is always 0 on my iphone. Not sure why.

I have managed to create a simple workaround in my code that does not use the velocity parameter that is working as intended. But this needs further investigation. 

Here is the code I added to the callback, so insted of using swipeX I use these calculations. Hope this can help others in similar problems until the issue is resolved. 

```
const sw = movement.x / elapsedTime;
const swiping = Math.abs(sw) > 0.8 ? Math.sign(sw) : 0;
```

**Comment by dbismut** [comment] 2020-12-22 13:40
@spoldman weird so if you log `vxvy` while dragging on the latest beta you get `[0,0]` always?

**Comment by spoldman** [comment] 2020-12-23 10:05
Yes that is the case, it is almost always [0, 0]

**Comment by dbismut** [comment] 2020-12-23 11:19
Only on iOS right? What's your iOS version?

**Comment by spoldman** [comment] 2020-12-23 15:32
I have tried Android and that works perfectly. I have a iPhone Xs and it is running iOS 14.3

**Comment by dbismut** [comment] 2020-12-23 21:26
Amazing I really can't explain. I'll try to set up a test sandbox tomorrow so that we can nail down the issue. Thanks for your help on this.

**Comment by mark-night** [comment] 2020-12-26 06:50
I can confirm the same issue on iPhone XS Max iOS 14.2

In most cases, vxvy has value of 0 when down===false, that is, if I try to log vxvy when !down, (try to do some logic based on velocity at the moment touch is released) , vxvy gives me value of 0. In rare cases, it has non zero value, didn't have a clue or pattern when the value will be non zero. In other words, I feel it is unreliable to implement some logic for condition !down.

Tried swipe state too, it works on desktop Chrome , but swipe never be detected on my iPhone, no matter what. BTW, it'd be really helpful if user can customize the default maximum 230ms duration for a gesture to be detected as a swipe rather than a drag.

Putting everything aside, I feel drag or swipe are really just different terms of the almost same thing, i.e., a swipe is just a short/quick drag. I found it is really confusing to have both. The thing really matters is the logic to implement for before and after touch/button is released, and what state is available for each scenario.

Let's imagine we are trying to scroll a long page with touch. When down===true, I want no animation but accurate locating (classic drag), i.e., set({props, immediate=true}). At the moment touch is released, I'd like to detect the velocity when !down, if it exceeds certain value, means user wants fast scroll (some animation to a projected position), otherwise, nothing. 

At first think, I thought I'd implement different logic for swipe and down. It did not work as the swipe issue mentioned above. And it wouldn't be perfect even if swipe works, imagine user slowly drag and then decide a fast scroll (pretty normal), in which case swipe detection would miss (exceeded 230ms switch) and only the velocity when !down would help, which unfortunately can not provide correct value for now.

**Comment by mark-night** [comment] 2020-12-26 08:32
Did another test which shows some interesting clue might be related:
if to log `movement` Y when `!down`, you get negative value if drag up (correct) but value 0 if drag down (should be some positive value). Same on iPhone or desktop Chrome.

version 9.0.0-beta.11
iPhone XS Max iOS 14.2
macOS 11.1
Chrome 87.0.4280.88

Didn't test movement X, didn't think necessary.

**Comment by dbismut** [comment] 2020-12-26 11:39
@mark-night @spoldman here is a sandbox that has the same logic as the one @spoldman submitted, only using plain divs instead of images (images can interfere with dragging although I doubt this is the problem in this case. Also, it only reacts to swipes, there's no 1:1 dragging movement involved here.

I've added a `console.log` that logs the time delta between each frame, and measures velocity "manually". On my device, it matches the velocity returned by `vxvy` (which isn't surprising since the maths are exactly the same). Can you please let me know what your logs say?

Here's an extract of my logs on Chrome in responsive mode for reference:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5003380/103150151-8ac56180-4771-11eb-869e-751a7f8d20b0.png">

Now I'll answer @mark-night comment. Swipe is not intended to check if the end velocity of the drag is superior to a velocity, which you can easily do with:

```js
if(state.last) const swipe = Math.abs(vx) > VELOCITY ? Math.sign(vx) : 0
```
 
In React UseGesture, `swipe` checks if the elapsed time is inferior to `250ms` (I've just pushed `9.0.0-beta.13` that adds `swipeDuration` as an [option](https://v9--use-gesture.netlify.app/docs/options/#swipeduration-drag-only), which I guess you could set to `Infinity`, and I've also changed the default duration from `220` to `250` and default minimum distance from `60` to `50`).

**Comment by mark-night** [comment] 2020-12-26 19:34
@dbismut 
Just a quick response via my phone, will test it out later and report back.

1. New duration option for swipe detection is definitely a good improve, will try it out if have chance.

2. I'm a little bit confused about your example for swipe detection. 
- What is the difference between last and !down? If they are not the same, is last the gesture frame right before !down?
- What is the recommended way to get the end velocity of a drag? Not velocity for the whole drag but the velocity at or close to the very moment when touch is released? I.e. , a long slow drag ends with a quick swipe should have a relatively fast end velocity. I tried to read velocity when !down, but as mentioned earlier, it's not stable, I got 0 for most of the time, and even when I get a non zero value, I couldn't find a clue how to reproduce it, particularly on my iPhone.
- Should I read velocity on state.last or velocity on !state.down for the end velocity of a drag?

Last, I don't see the sandbox link, might because I'm reading this in mobile app? Don't have access to my computer right now, will check it out later.

Thanks for the quick response. Really appreciated.

**Comment by mark-night** [comment] 2020-12-26 19:49
Just wanted to comment a little more in case I'm causing confusion:

I'm not intend to detect a swipe, but rather trying to detect the end velocity of a drag.

**Comment by dbismut** [comment] 2020-12-26 20:47
@mark-night oooops updated my message with the [sandbox link](https://codesandbox.io/s/vibrant-hugle-le03d) sorry 😅

> What is the difference between last and !down? If they are not the same, is last the gesture frame right before !down?

That's a good question, and `down` behaviour is going to change in the next major release to be more consistent with what it should represent.

`down` is an indicator flagging if one or more mouse buttons are pressed or if one or more fingers are in contact with the screen. In most cases `down` will be `false` when the drag ends, but in `v9` when you programmatically `cancel()` the drag, `down` will still be `true` until the user in fact releases the pointer. Also, you can imagine dragging with one finger, adding a second finger to pinch, releasing the first finger initiating the drag. The drag gesture will end, but `down` should still be `true` as one finger is still pressing the screen.

A safer alternative to `down` in general is `active` (I tried to update most sandbox with `active` and v9 docs will show `active` instead of `down`).

`last` is fired only once, at the last frame of the gesture, and only if the drag was started. In other words, if no drag has was recognised, `last` will never be `true`.

So you might ask when does that even happen, and what's the difference between `!active` and `last`. Well `active` can be `false` in situations where `last` is also `false`: that might be the case when you use the `filterTaps` option, which will trigger your handler on a simple click with `{ tap: true, active: false, last: false }`. This is a situation where the drag hasn't started but you still want your handler to detect taps / clicks.

> What is the recommended way to get the end velocity of a drag? Not velocity for the whole drag but the velocity at or close to the very moment when touch is released?

It should be:

```js
if(state.last) const releaseVelocity = state.vxvy
```

Now this may have some limits, as it measures the velocity between the last and the one-before-last moving frames. It *could* be improved if we'd measure the average velocity from the last `X` frames (with `X` being a small number), but for now it's just the last two. 

Hope this helps!

**Comment by mark-night** [comment] 2020-12-26 21:33
Wow, that makes a lot more sense now, and everything feels clear. I guess I just got trapped in `down` magic too deep... ;-p

So if I understand this correctly, along the timeline, here are how everything change in order:
1. `tap` and `down` with `active` (since first touch/click)
2. `swipe` before exceeding threshold
3. dragging 
4. `active` (to `false`) and `last` (only once), `down` (to `false`) if no more touching or butting down

Thank you for making this clear!

**Comment by dbismut** [comment] 2020-12-26 22:07
The logic is a bit more complex 😅 

- `swipe` only gets computed when the pointer is released. 
- `tap` shouldn't be used without the `filterTaps` option (the order you assumed is correct, but `tap` will be set to `false` as soon as the gesture distance is over `3px`). 

There's a few other subtle things but that's it really!

**Comment by mark-night** [comment] 2020-12-27 00:37
> The logic is a bit more complex 😅
> 
> * `swipe` only gets computed when the pointer is released.
> * `tap` shouldn't be used without the `filterTaps` option (the order you assumed is correct, but `tap` will be set to `false` as soon as the gesture distance is over `3px`).
> 
> There's a few other subtle things but that's it really!

Thanks for further clarifying this, well noted. I got the idea, was just too lazy to type more details as was typing on my phone... what a good excuse...

Now back to the sandbox test feedback:

On my **desktop** (Chrome 87.0.4280.88 on macOS 11.1), it behaves pretty much the same as what your screenshot shows, except that the last log for **every** swipe always gets a `0` for the `manualVX` with `vx` being the same value as the second last log.

The issue first reported was actually unexpected behavior on **iPhone** (mine is an iPhone Xs Max iOS 14.2):
Swipe is veeeery hard to be detected/triggered, I tried more than a dozen swipes, only got one detected. The log looks like below (with repeated similar logs removed): (a short screen cast video is available here [https://youtu.be/dN77pcTGyOQ](https://youtu.be/dN77pcTGyOQ ) sorry I don't know how to display my gesture, but if you pay attention to the log scroll pace, you can guess my swiping)
_▶{deltaStamp: 0, manualVX: -Infinity, vx: -0.5454545454545454}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -1, vx: -1}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 17, manualVX: -1.411764705882353, vx: -1.4117647058823528}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -1.9375, vx: -1.9375}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 17, manualVX: -1.9411764705882353, vx: -1.9411764705882353}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -1.5625, vx: -1.5625}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 18, manualVX: -1, vx: -1}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8, manualVX: 0, vx: 0}
▶{deltaStamp: 0, manualVX: -Infinity, vx: -1.125}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -1.875, vx: -1.875}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 18, manualVX: -2.5, vx: -2.5}
▶{deltaStamp: 16, manualVX: -2.75, vx: -2.75}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -1.5, vx: -1.5}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 6, manualVX: 0, vx: 0}
▶{deltaStamp: 0, manualVX: -Infinity, vx: -1.1176470588235294}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8.000000000001819, manualVX: -1.8749999999995737, vx: -1.8749999999995737}
▶{deltaStamp: 16.99999999999818, manualVX: -2.470588235294382, vx: -2.470588235294382}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -3.1875, vx: -3.1875}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8, manualVX: -3.125, vx: -3.125}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 9, manualVX: 0, vx: 0}
▶{deltaStamp: 0, manualVX: -Infinity, vx: -1.2000000000000872}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8, manualVX: -2.375, vx: -2.375}
▶{deltaStamp: 17, manualVX: -2.8823529411764706, vx: -2.8823529411764706}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 17, manualVX: -2.9411764705882355, vx: -2.941176470588235}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 7, manualVX: 0, vx: 0}
▶{deltaStamp: 0, manualVX: -Infinity, vx: -0.8}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8.000000000001819, manualVX: -1.6249999999996305, vx: -1.6249999999996305}
▶{deltaStamp: 16.99999999999818, manualVX: -2.235294117647298, vx: -2.235294117647298}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -3.375, vx: -3.375}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 17, manualVX: -3.235294117647059, vx: -3.235294117647059}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8, manualVX: 0, vx: 0}
▶{deltaStamp: 0, manualVX: -Infinity, vx: -1.7142857142861598}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 9.000000000001819, manualVX: -1.4444444444441524, vx: -1.4444444444441524}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16.99999999999818, manualVX: -2.294117647059069, vx: -2.294117647059069}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 17, manualVX: -2.823529411764706, vx: -2.8235294117647056}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 16, manualVX: -3.125, vx: -3.125}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 8, manualVX: -2.25, vx: -2.25}
▶{deltaStamp: 0, manualVX: NaN, vx: 0}
▶{deltaStamp: 6.000000000001819, manualVX: 0, vx: 0}

**Comment by mark-night** [comment] 2020-12-27 00:40
Forgot to mention, the above iPhone test was done in Chrome for iOS, tried Safari too, same.

**Comment by dbismut** [comment] 2020-12-27 08:52
@mark-night Many thanks for this, much appreciated. There's obviously something wrong wherever `manualVX` is NaN. It looks like there one event would trigger the handler twice. I've updated the sandbox again, can you please paste the logs? Here's what I get (I've fixed the precision to 3 digits so this is more readable):

<img width="710" alt="image" src="https://user-images.githubusercontent.com/5003380/103167156-e7378800-4828-11eb-9266-286260324256.png">

> On my desktop (Chrome 87.0.4280.88 on macOS 11.1), it behaves pretty much the same as what your screenshot shows, except that the last log for every swipe always gets a 0 for the manualVX with vx being the same value as the second last log.

That is normal, my naive implementation of `manualVX` computes velocity between the last `pointermove` event and the `pointerup` event, which obviously happen at the same position so it's always `0`. But `vxvy` in the lib implementation keeps track of the last frame velocity which is what you want.

**Comment by mark-night** [comment] 2020-12-27 18:44
Here you go. Still, swipe hard to be detected.

```
▶{dx: -22, manualVX: -Infinity, _pointerId: 1785950170, type: "pointermove", timestamp: 5153.000000000001…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5153.000000000001…}
▶{dx: -28, manualVX: -1.867, _pointerId: 1785950170, type: "pointermove", timestamp: 5168…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5168…}
▶{dx: -46, manualVX: -2.706, _pointerId: 1785950170, type: "pointermove", timestamp: 5185.000000000001…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5185.000000000001…}
▶{dx: -48, manualVX: -2.667, _pointerId: 1785950170, type: "pointermove", timestamp: 5203…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5203…}
▶{dx: -34, manualVX: -2.125, _pointerId: 1785950170, type: "pointermove", timestamp: 5219…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5219…}
▶{dx: -20, manualVX: -1.25, _pointerId: 1785950170, type: "pointermove", timestamp: 5235…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5235…}
 dx: 0
 manualVX: NaN
 _pointerId: 1785950170
 type: "pointermove"
 timestamp: 5235
 vx: 0
▶{dx: -5, manualVX: -0.5, _pointerId: 1785950170, type: "pointermove", timestamp: 5245…}
▶{dx: 0, manualVX: NaN, _pointerId: 1785950170, type: "pointermove", timestamp: 5245…}
 dx: 0
 manualVX: NaN
 _pointerId: 1785950170
 type: "pointermove"
 timestamp: 5245
 vx: 0

```

**Comment by mark-night** [comment] 2020-12-28 05:19
Just discovered a suspicious behavior that might be related, I found it's way more easier for a swipe to be detected on my iPhone if I *swipe gently enough*, i.e. swipe with much less force than I usually do.

Feels like iPhone's force touch feature is somehow interfering with gesture detection. 

@dbismut

**Comment by mark-night** [comment] 2020-12-28 05:28
@dbismut @spoldman 

If I disable iPhone's 3D Touch setting (Settings/Accessibility/Touch/3D & Haptic Touch/3D Touch), then swipe works as perfect as on desktop browser.

Don't know if this can be tweaked/opt-out by some logic within the library, as you can not assume user has the feature turned off. Most won't, I guess.

**Comment by dbismut** [comment] 2020-12-28 09:22
Oh that might explain a lot of things and I would never have found that out by myself. If I remember correctly the iPhone X has a different 3D Touch implementation from iPhone 11 / 12.

Just to clarify I didn't implement any fix in the sandbox so you shouldn't see any improvement with how it behaves. 

What you can notice though is that you have two subsequent pointermove events with the SAME timestamp. Since the lib uses the timestamp delta to calculate the velocity, we get a NaN value.

I'll work on a fix but very likely I'll skip event that have the same timestamp as the previous one.

**Comment by dbismut** [comment] 2020-12-28 12:10
@mark-night @spoldman I've released 9.0.0-beta.14 that attempts at fixing this. Can you please try the same sandbox and report the logs once more? https://codesandbox.io/s/vibrant-hugle-le03d

Thanks so much for your help, much appreciated.

**Comment by mark-night** [comment] 2020-12-28 19:52
Worked perfectly like a charm. Thank you @dbismut, great job!

FYI, I remember reading somewhere that Apple has actually removed 3D Touch since iPhone 11. Since it was released with iPhone 6s, there should still be many users using it, so it's worth a fix.

It's a great example of great design doesn't always get adopted....

Here is some of the log I got:
```

▶{dx: -10, manualVX: -0.625, _pointerId: 1683546974, type: "pointermove", timestamp: 10231…}
▶{dx: -16, manualVX: -1, _pointerId: 1683546974, type: "pointermove", timestamp: 10247…}
▶{dx: -22, manualVX: -1.294, _pointerId: 1683546974, type: "pointermove", timestamp: 10264…}
▶{dx: -23, manualVX: -1.353, _pointerId: 1683546974, type: "pointermove", timestamp: 10281…}
▶{dx: -25, manualVX: -1.471, _pointerId: 1683546974, type: "pointermove", timestamp: 10298…}
▶{dx: -24, manualVX: -1.5, _pointerId: 1683546974, type: "pointermove", timestamp: 10314…}
▶{dx: -7, manualVX: -0.778, _pointerId: 1683546974, type: "pointermove", timestamp: 10323…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546974, type: "pointerup", timestamp: 10330…}
▶{dx: -18, manualVX: -Infinity, _pointerId: 1683546975, type: "pointermove", timestamp: 11231…}
▶{dx: -36, manualVX: -1.059, _pointerId: 1683546975, type: "pointermove", timestamp: 11265…}
▶{dx: -24, manualVX: -1.5, _pointerId: 1683546975, type: "pointermove", timestamp: 11281…}
▶{dx: -25, manualVX: -1.471, _pointerId: 1683546975, type: "pointermove", timestamp: 11298…}
▶{dx: -21, manualVX: -1.235, _pointerId: 1683546975, type: "pointermove", timestamp: 11315…}
▶{dx: -15, manualVX: -0.938, _pointerId: 1683546975, type: "pointermove", timestamp: 11331…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546975, type: "pointerup", timestamp: 11340…}
▶{dx: -13, manualVX: -Infinity, _pointerId: 1683546976, type: "pointermove", timestamp: 12048…}
▶{dx: -12, manualVX: -0.706, _pointerId: 1683546976, type: "pointermove", timestamp: 12065…}
▶{dx: -18, manualVX: -1.125, _pointerId: 1683546976, type: "pointermove", timestamp: 12081…}
▶{dx: -26, manualVX: -1.529, _pointerId: 1683546976, type: "pointermove", timestamp: 12098…}
▶{dx: -55, manualVX: -1.667, _pointerId: 1683546976, type: "pointermove", timestamp: 12131…}
▶{dx: -21, manualVX: -1.313, _pointerId: 1683546976, type: "pointermove", timestamp: 12147…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546976, type: "pointerup", timestamp: 12156…}
▶{dx: -12, manualVX: -Infinity, _pointerId: 1683546977, type: "pointermove", timestamp: 12823…}
▶{dx: -5, manualVX: -0.556, _pointerId: 1683546977, type: "pointermove", timestamp: 12832…}
▶{dx: -14, manualVX: -0.875, _pointerId: 1683546977, type: "pointermove", timestamp: 12848…}
▶{dx: -22, manualVX: -1.375, _pointerId: 1683546977, type: "pointermove", timestamp: 12864…}
▶{dx: -31, manualVX: -1.824, _pointerId: 1683546977, type: "pointermove", timestamp: 12881…}
▶{dx: -36, manualVX: -2, _pointerId: 1683546977, type: "pointermove", timestamp: 12899…}
▶{dx: -33, manualVX: -2.062, _pointerId: 1683546977, type: "pointermove", timestamp: 12915.000000000002…}
▶{dx: -18, manualVX: -1.125, _pointerId: 1683546977, type: "pointermove", timestamp: 12931.000000000002…}
▶{dx: -9, manualVX: -0.563, _pointerId: 1683546977, type: "pointermove", timestamp: 12947.000000000002…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546977, type: "pointerup", timestamp: 12956…}
▶{dx: -24, manualVX: -Infinity, _pointerId: 1683546978, type: "pointermove", timestamp: 14231…}
▶{dx: -17, manualVX: -0.944, _pointerId: 1683546978, type: "pointermove", timestamp: 14249…}
▶{dx: -25, manualVX: -1.563, _pointerId: 1683546978, type: "pointermove", timestamp: 14265…}
▶{dx: -29, manualVX: -1.813, _pointerId: 1683546978, type: "pointermove", timestamp: 14281…}
▶{dx: -27, manualVX: -1.588, _pointerId: 1683546978, type: "pointermove", timestamp: 14298…}
▶{dx: -22, manualVX: -1.294, _pointerId: 1683546978, type: "pointermove", timestamp: 14315…}
▶{dx: -13, manualVX: -0.765, _pointerId: 1683546978, type: "pointermove", timestamp: 14332…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546978, type: "pointerup", timestamp: 14340…}
▶{dx: 4, manualVX: Infinity, _pointerId: 1683546988, type: "pointermove", timestamp: 39251…}
▶{dx: 9, manualVX: 0.529, _pointerId: 1683546988, type: "pointermove", timestamp: 39268…}
▶{dx: 14, manualVX: 0.824, _pointerId: 1683546988, type: "pointermove", timestamp: 39285.00000000001…}
▶{dx: 17, manualVX: 1.063, _pointerId: 1683546988, type: "pointermove", timestamp: 39301…}
▶{dx: 16, manualVX: 0.941, _pointerId: 1683546988, type: "pointermove", timestamp: 39318…}
▶{dx: 16, manualVX: 0.941, _pointerId: 1683546988, type: "pointermove", timestamp: 39335…}
▶{dx: 18, manualVX: 1.059, _pointerId: 1683546988, type: "pointermove", timestamp: 39352.00000000001…}
▶{dx: 22, manualVX: 1.375, _pointerId: 1683546988, type: "pointermove", timestamp: 39368…}
▶{dx: 9, manualVX: 1.125, _pointerId: 1683546988, type: "pointermove", timestamp: 39376…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546988, type: "pointerup", timestamp: 39385…}
▶{dx: 10, manualVX: Infinity, _pointerId: 1683546989, type: "pointermove", timestamp: 39993…}
▶{dx: 5, manualVX: 0.625, _pointerId: 1683546989, type: "pointermove", timestamp: 40001…}
▶{dx: 15, manualVX: 0.882, _pointerId: 1683546989, type: "pointermove", timestamp: 40018…}
▶{dx: 17, manualVX: 1.063, _pointerId: 1683546989, type: "pointermove", timestamp: 40034…}
▶{dx: 18, manualVX: 1, _pointerId: 1683546989, type: "pointermove", timestamp: 40052…}
▶{dx: 18, manualVX: 1.125, _pointerId: 1683546989, type: "pointermove", timestamp: 40068…}
▶{dx: 23, manualVX: 1.438, _pointerId: 1683546989, type: "pointermove", timestamp: 40084…}
▶{dx: 22, manualVX: 1.222, _pointerId: 1683546989, type: "pointermove", timestamp: 40102.00000000001…}
▶{dx: 18, manualVX: 1.125, _pointerId: 1683546989, type: "pointermove", timestamp: 40118…}
▶{dx: 16, manualVX: 0.941, _pointerId: 1683546989, type: "pointermove", timestamp: 40135…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546989, type: "pointerup", timestamp: 40143…}
▶{dx: 13, manualVX: Infinity, _pointerId: 1683546990, type: "pointermove", timestamp: 40635…}
▶{dx: 12, manualVX: 0.706, _pointerId: 1683546990, type: "pointermove", timestamp: 40652…}
▶{dx: 21, manualVX: 1.313, _pointerId: 1683546990, type: "pointermove", timestamp: 40668…}
▶{dx: 25, manualVX: 1.563, _pointerId: 1683546990, type: "pointermove", timestamp: 40684…}
▶{dx: 23, manualVX: 1.278, _pointerId: 1683546990, type: "pointermove", timestamp: 40702…}
▶{dx: 24, manualVX: 1.5, _pointerId: 1683546990, type: "pointermove", timestamp: 40718…}
▶{dx: 33, manualVX: 1.941, _pointerId: 1683546990, type: "pointermove", timestamp: 40735…}
▶{dx: 34, manualVX: 2.125, _pointerId: 1683546990, type: "pointermove", timestamp: 40751…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546990, type: "pointerup", timestamp: 40759…}
▶{dx: 7, manualVX: Infinity, _pointerId: 1683546991, type: "pointermove", timestamp: 41302…}
▶{dx: 10, manualVX: 0.625, _pointerId: 1683546991, type: "pointermove", timestamp: 41318…}
▶{dx: 26, manualVX: 1.529, _pointerId: 1683546991, type: "pointermove", timestamp: 41335…}
▶{dx: 35, manualVX: 2.188, _pointerId: 1683546991, type: "pointermove", timestamp: 41351…}
▶{dx: 33, manualVX: 1.833, _pointerId: 1683546991, type: "pointermove", timestamp: 41369…}
▶{dx: 40, manualVX: 2.5, _pointerId: 1683546991, type: "pointermove", timestamp: 41385…}
▶{dx: 37, manualVX: 2.313, _pointerId: 1683546991, type: "pointermove", timestamp: 41401…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546991, type: "pointerup", timestamp: 41410.00000000001…}
▶{dx: 42, manualVX: Infinity, _pointerId: 1683546992, type: "pointermove", timestamp: 42310…}
▶{dx: 14, manualVX: 1.75, _pointerId: 1683546992, type: "pointermove", timestamp: 42318…}
▶{dx: 33, manualVX: 1.941, _pointerId: 1683546992, type: "pointermove", timestamp: 42335…}
▶{dx: 37, manualVX: 2.176, _pointerId: 1683546992, type: "pointermove", timestamp: 42352.00000000001…}
▶{dx: 37, manualVX: 2.176, _pointerId: 1683546992, type: "pointermove", timestamp: 42369…}
▶{dx: 19, manualVX: 2.714, _pointerId: 1683546992, type: "pointermove", timestamp: 42376…}
▶{dx: 0, manualVX: 0, _pointerId: 1683546992, type: "pointerup", timestam......
```

**Comment by mark-night** [comment] 2020-12-28 19:55
BTW, how do I update to the latest version with the fix? I tried `npm update` which still gives me beta 11?

**Comment by mark-night** [comment] 2020-12-28 20:23
> BTW, how do I update to the latest version with the fix? I tried `npm update` which still gives me beta 11?

Never mind, was able  to find out (`npm view`) it's the `@next` tag

**Comment by dbismut** [comment] 2020-12-28 20:26
Great that it works! I'm a bit worried that `manualVX` gives you Infinity as a value though. Does `vxvy` have the same value?

**Comment by mark-night** [comment] 2020-12-28 20:47
> Great that it works! I'm a bit worried that `manualVX` gives you Infinity as a value though. Does `vxvy` have the same value?

Sorry forgot to expand the log. 

- Yes, `vx` does have the same value as `manualVX`, except the last gesture frame for every swipe, where `manualVX` is 0 while `vx` has the same value as previous gesture frame. As you've explained this earlier, I guess it doesn't matter. I don't feel anything broken. 
- `manualVX` does give Infinity on every first gesture frame while `vx` doesn't. Again, I don't see anything broken due to that neither.

![IMG_2294](https://user-images.githubusercontent.com/48889700/103242360-c5aecd00-490a-11eb-83a7-6b5d83441779.jpg)

**Comment by dbismut** [comment] 2020-12-28 20:50
Perfect! Thanks!

**Comment by mark-night** [comment] 2020-12-28 20:55
My pleasure! 
Thanks for providing this great library! Switched from react-swipeable, although it took me sometime to understand everything at the beginning, but after all, I feel it's worth the switch as I feel react-use-gesture is more flexible (fine grained) and controllable. Great work!

**Comment by dbismut** [comment] 2020-12-28 21:01
Always nice to hear! Let me know if there's anything else not working for you. Should be able to release v9 in the next few days. Cheers!

**Comment by mark-night** [comment] 2020-12-28 21:12
I do like to take the chance to suggest considering appending to the documentation somewhere, to explain/demonstrate those `boolean` type gesture states (intentional, first, last, active, down, dragging, wheeling......) along event timeline, when and how they are available/modified, and if they are set only once or multiple times, etc. I feel these boolean states are really what shines react-use-gesture and makes many things possible, but unfortunately aren't explained very clearly in the documentation. 
Another cool feature is the `memo` state, again, very powerful but takes a while to see the power because doc doesn't covers it clearly. I'd have missed it totally if I didn't read your sandbox test code for this issue... I was trying to implement both onWheel and onDrag on the same DOM, where a gesture result would interferes initial of another. I had to manually manipulate initial for both, until I suddenly understand what `memo` is meant for from reading your code... I still have to manipulate initial for both, but with `memo`, it is very easy to do.

**Comment by dbismut** [comment] 2020-12-28 21:16
Good point. `initial` should cover the most common use case for memo, but indeed it's an obscure feature that might need some more love. I was planning to make a storybook with more examples to play with. The chronology of events is a great idea.

**Comment by mark-night** [comment] 2020-12-28 22:08
> Good point. `initial` should cover the most common use case for `memo`, but indeed it's an obscure feature that might need some more love. I was planning to make a storybook with more examples to play with. The chronology of events is a great idea.

Looking forward to the updates.
`initial` manipulation is a must if multiple gestures are to be deployed on the same DOM. Just like the `useGestures` hook, when you need it, you'll thank for its being there already. =)

**Comment by spoldman** [comment] 2021-01-04 10:37
Sorry for late reply as I wasn't much in front of the computer during the hollidays but I tested out the fix just now and it worked like charm, thanks for all the hard work :)

**Comment by zvictor** [comment] 2021-01-12 11:15
I was having the same issue described here but `9.0.0-beta.14` has solved it.
It seems safe to close the issue.

**Comment by dbismut** [comment] 2021-01-12 12:18
As soon as I release the 9.0.0 version I'll close pending issues.

**Closed** 2021-01-13 16:22 UTC
Labels: fix coming
